blank_issues_enabled: true
contact_links:
  - name: "🌍 النقاش التأسيسي للمجتمع"
    url: "https://github.com/tadabburmag/tadabburjournal/issues/1"
    about: "إذا كانت لديك فكرة عامة أو تريد التعرف إلى المشروع، ابدأ من هنا."
